### ISSUE TITLE
`activator` deployment container doesn't go to `READY` in airgap

### ISSUE THREAD

**Issue by orfeas-k** [canonical/knative-operators#151] opened 2023-09-05 08:13 UTC
We stumbled upon this issue during testing knative in airgap environment (#140). This was thoroughly documented in this comment https://github.com/canonical/knative-operators/issues/140#issuecomment-1706120590.

In short, we see those logs in `CoreDNS` pod 
```bash
[INFO] 10.1.205.153:40339 - 44253 "AAAA IN autoscaler.knative-serving.svc.cluster.local.lxd. udp 66 false 512" - - 0 2.000241772s
[INFO] 10.1.205.153:56166 - 44510 "A IN autoscaler.knative-serving.svc.cluster.local.lxd. udp 66 false 512" - - 0 2.000258023s
[ERROR] plugin/errors: 2 autoscaler.knative-serving.svc.cluster.local.lxd. AAAA: read udp 10.1.205.163:34994->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 autoscaler.knative-serving.svc.cluster.local.lxd. A: read udp 10.1.205.163:34020->8.8.4.4:53: i/o timeout
```
for which we believe that requests to `8.8.x.x` have a slow response in our cluster and that results in a timeout that blocks the container from going to `READY`. For this, we will need to configure appropriately our airgapped environmnent.

**Comment by NohaIhab** [comment] 2023-09-25 08:37
I was not able to reproduce this with the activator image `activator:c3bbf3a96920048869dcab8e133e00f59855670b8a0bbca3d72ced2f512eb5e1`
do you know which image it was when you got this error ? @orfeas-k 

here's the logs from my container:
```
microk8s kubectl logs activator-7cf459cb4-wpzz8 -n knative-serving
2023/09/25 08:18:45 Registering 3 clients
2023/09/25 08:18:45 Registering 3 informer factories
2023/09/25 08:18:45 Registering 3 informers
{"severity":"INFO","timestamp":"2023-09-25T08:18:45.434807018Z","logger":"activator","caller":"activator/main.go:141","message":"Starting the knative activator","commit":"e82287d","knative.dev/controller":"activator","knative.dev/pod":"activator-7cf459cb4-wpzz8"}
{"severity":"INFO","timestamp":"2023-09-25T08:18:45.438116683Z","logger":"activator","caller":"activator/main.go:218","message":"Connecting to Autoscaler at ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"e82287d","knative.dev/controller":"activator","knative.dev/pod":"activator-7cf459cb4-wpzz8"}
{"severity":"INFO","timestamp":"2023-09-25T08:18:45.438283209Z","logger":"activator","caller":"websocket/connection.go:161","message":"Connecting to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"e82287d","knative.dev/controller":"activator","knative.dev/pod":"activator-7cf459cb4-wpzz8"}
{"severity":"INFO","timestamp":"2023-09-25T08:18:45.438383359Z","logger":"activator","caller":"profiling/server.go:64","message":"Profiling enabled: false","commit":"e82287d","knative.dev/controller":"activator","knative.dev/pod":"activator-7cf459cb4-wpzz8"}
{"severity":"INFO","timestamp":"2023-09-25T08:18:45.443356799Z","logger":"activator","caller":"activator/request_log.go:45","message":"Updated the request log template.","commit":"e82287d","knative.dev/controller":"activator","knative.dev/pod":"activator-7cf459cb4-wpzz8","template":""}
```

**Comment by kimwnasptd** [comment] 2023-09-25 09:58
@NohaIhab you mean that the activator Pod always has all containers running and ready?

Could you have maybe first applied the DNS changes described in https://github.com/canonical/bundle-kubeflow/issues/703#issuecomment-1729826733 and that's why you don't see this anymore?

Also, if you check the logs from CoreDNS do you still see similar timeout logs as mentioned in the first message for the domain `autoscaler.knative-serving.svc.cluster.local.lxd.`?

**Comment by NohaIhab** [comment] 2023-09-25 13:20
There are no timeout logs in the CoreDNS. As of the latest changes with setting the DNS correctly, this error does not take place. Closing.

**Closed by NohaIhab** 2023-09-25 13:20 UTC
Labels: bug
